Song = [
 {   'id':0,
     'name':'Overture',
     'artist':'Bear McCreary',
     'album':'SoundTrack God of War',
     'year':'2018',
     'image':'https://m.media-amazon.com/images/I/81+LL+EHCvL._SS500_.jpg',
     'spotify':'https://open.spotify.com/embed/track/6ZMwwuUOx8kefl32gWOjtY',
     'youtube':'https://www.youtube.com/embed/cjxfk7JNNDI'}
,
     {'id':1,
     'name':'Death With Dignity',
     'artist':'Sufjan Stevens',
     'album':'Carrie and Lowell',
     'year':'2014',
     'image':'https://upload.wikimedia.org/wikipedia/en/e/ec/Sufjan_Stevens_-_Carrie_%26_Lowell.jpg',
     'spotify':'https://open.spotify.com/embed/track/4fpEuKIzTLmMJnYwFU0oqr',
     'youtube':'https://www.youtube.com/embed/9h6gQVxJO9w'}
,
         {'id':2,
     'name':'Alma mía',
     'artist':'Natalia Lafourcade',
     'album':'Musas',
     'year':'2018',
     'image':'https://upload.wikimedia.org/wikipedia/en/a/ad/Musas_by_Natalia_Lafourcade.jpg',
     'spotify':'https://open.spotify.com/embed/track/7qVnzohY8VAKFkiJIgStbk',
     'youtube':'https://www.youtube.com/embed/zZGF3vRDyIE'}
,
         {'id':3,
     'name':'The Last of Us',
     'artist':'Gustavo Santaolalla',
     'album':'SoundTrack The Last of Us',
     'year':'2013',
     'image':'https://images-na.ssl-images-amazon.com/images/I/61SvF5WJAmL._SL1223_.jpg',
     'spotify':'https://open.spotify.com/embed/track/285ieonEuLkll3zknYK2TY',
     'youtube':'https://www.youtube.com/embed/b5DQ6mzFNyE'}
,
      {'id':4,
     'name':'Nude',
     'artist':'Radiohead',
     'album':'In Rainbows',
     'year':'2007',
     'image':'https://upload.wikimedia.org/wikipedia/en/1/14/Inrainbowscover.png',
     'spotify':'https://open.spotify.com/embed/track/5k7VKj1Xwy5DjO4B0PdAOb',
     'youtube':'https://www.youtube.com/embed/BbWBRnDK_AE'}
]
